/* ╔═══ BLOCCO 1 — GLOSSARIO ══════════════════════════════════╗
   it / en = le due forme principali. alias = tutto ciò che va
   riconosciuto nel testo, in entrambe le lingue.
   ╚═══════════════════════════════════════════════════════════╝ */
const GLOSSARIO = [
{id:"spin-go",it:"Spin & Go",en:"Spin & Go",cat:"Formato",
 alias:["spin & go","spin&go","spin and go","spin go","spin"],
 breve:"Sit &amp; go iper-turbo da tre giocatori in cui il montepremi viene sorteggiato a inizio partita.",
 lungo:"<p>Torneo lampo con stack corti e livelli velocissimi. Prima della prima mano una ruota sorteggia un moltiplicatore che determina il montepremi: quasi sempre due o tre volte il buy-in, molto di rado migliaia di volte.</p><p>Si comincia in tre e si finisce testa a testa, quindi servono entrambe le competenze. E una fetta importante del rendimento arriva da moltiplicatori rari, il che rende la varianza enorme.</p>",
 vedi:["moltiplicatore","varianza","heads-up"]},

{id:"moltiplicatore",it:"Moltiplicatore",en:"Multiplier",cat:"Formato",
 alias:["moltiplicatore","moltiplicatori","multiplier","spinner"],
 breve:"Il numero sorteggiato a inizio partita che stabilisce il montepremi, lo stack e la durata dei livelli.",
 lungo:"<p>Non decide solo quanto si vince. Dal novembre 2024 su PokerStars determina anche le fiches di partenza e la velocità dei bui: x2 e x3 partono con 15 bui, dal x4 con 20, dal x10 con 25.</p><p>Cambia anche la struttura dei premi: fino al x3 vince tutto il primo, dal x10 in su pagano tre posizioni.</p>",
 vedi:["spin-go","stack-effettivo","icm"]},

{id:"varianza",it:"Varianza",en:"Variance",cat:"Mentale",
 alias:["varianza","variance","swing","swings"],
 breve:"L'oscillazione dei risultati intorno al valore vero: quanto il breve periodo può mentire.",
 lungo:"<p>Su questo formato è estrema, perché una parte del guadagno atteso arriva da moltiplicatori che escono una volta ogni migliaia di partite. Fino a che quelli non escono, un giocatore vincente sembra perdente.</p><p>Conseguenza pratica: poche centinaia di partite non dicono nulla sul tuo livello. Nemmeno mille. Giudicare la propria bravura dal saldo del mese è il modo più rapido per cambiare strategia nel momento sbagliato.</p>",
 vedi:["bankroll","valore-atteso"]},

{id:"bankroll",it:"Bankroll",en:"Bankroll",cat:"Mentale",
 alias:["bankroll","cassa di gioco"],
 breve:"I soldi destinati esclusivamente al gioco, separati da tutto il resto.",
 lungo:"<p>La regola di gestione serve a sopravvivere alla varianza, non a moltiplicare i soldi. Su un formato con oscillazioni così ampie servono molte più iscrizioni di riserva rispetto a un torneo normale.</p><p>Un bankroll troppo piccolo non ti fa perdere per sfortuna: ti fa giocare male, perché ogni mano pesa troppo.</p>",
 vedi:["varianza"]},

{id:"bottone",it:"Bottone",en:"Button",cat:"Posizioni",
 alias:["bottone","button","btn","da bottone","dal bottone"],
 breve:"La posizione che agisce per ultima dopo il flop. In tre giocatori è la prima a parlare prima del flop.",
 lungo:"<p>La posizione migliore del tavolo: dopo il flop decide avendo già visto cosa fanno gli altri, e al tavolo da tre è l'unica senza buio da versare.</p><p>Questo vantaggio giustifica un range di apertura molto largo: mani che altrove butteresti qui rendono, perché la posizione ti ripaga nelle strade successive.</p>",
 vedi:["posizione","range-apertura"]},

{id:"small-blind",it:"Piccolo buio",en:"Small blind",cat:"Posizioni",
 alias:["piccolo buio","small blind","sb","piccolo bui"],
 breve:"Versa il buio piccolo. In tre giocatori parla per secondo prima del flop e per primo dopo.",
 lungo:"<p>La posizione più scomoda: mette soldi al buio e dopo il flop parla per prima. Ha però già investito metà buio grande, quindi il prezzo per continuare è più basso.</p><p>È l'unica posizione in cui, nelle tabelle di questa serie, compare anche il limp come scelta deliberata.</p>",
 vedi:["big-blind","limp","posizione"]},

{id:"big-blind",it:"Grande buio",en:"Big blind",cat:"Posizioni",
 alias:["grande buio","big blind","bb","grandi bui"],
 breve:"Versa il buio grande. È l'ultimo a parlare prima del flop e ha le quote migliori per difendersi.",
 lungo:"<p>Ha già un buio intero nel piatto. Se il bottone apre a due bui, per vedere ne aggiunge uno e ne può vincere due e mezzo: quote che permettono di difendersi con mani molto più deboli di quelle con cui apriresti.</p><p>Attenzione all'ambiguità: grande buio è sia la posizione sia l'unità di misura degli stack.</p>",
 vedi:["difesa-bb","quote-del-piatto"]},

{id:"heads-up",it:"Testa a testa",en:"Heads-up",cat:"Posizioni",
 alias:["testa a testa","heads-up","heads up","hu"],
 breve:"Il gioco a due, quando uno dei tre è stato eliminato.",
 lungo:"<p>Ogni Spin &amp; Go che non finisce con un'eliminazione doppia passa da qui, quindi è metà del formato e non un dettaglio finale.</p><p>A due i range si allargano enormemente e con stack corti si scivola quasi subito nel push o fold.</p>",
 vedi:["push-fold","spin-go"]},

{id:"posizione",it:"Posizione",en:"Position",cat:"Concetti",
 alias:["posizione","posizionale","in posizione","fuori posizione","position","out of position","oop","ip"],
 breve:"Chi agisce dopo l'avversario è in posizione, e decide avendo più informazioni.",
 lungo:"<p>Parlare per ultimi permette di vedere l'azione prima di scegliere, di controllare la dimensione del piatto e di bluffare sapendo che nessuno può più reagire.</p><p>Quasi tutte le differenze tra i range delle varie posizioni nascono da qui.</p>",
 vedi:["bottone","big-blind"]},

{id:"range",it:"Range",en:"Range",cat:"Concetti",
 alias:["range","ventaglio di mani"],
 breve:"L'insieme di tutte le mani con cui compi una certa azione in una certa situazione.",
 lungo:"<p>Non giochi una mano alla volta, giochi un insieme. Il range è la lista completa delle mani con cui apriresti, pagheresti o passeresti in quella situazione, e si rappresenta con la griglia delle 169 combinazioni.</p><p>Ragionare per range invece che per mani singole è il salto mentale più importante del poker moderno.</p>",
 vedi:["range-apertura","combo","cappato"]},

{id:"range-apertura",it:"Range di apertura",en:"Opening range",cat:"Preflop",
 alias:["range di apertura","range d'apertura","apertura","opening range","open","raise first in","rfi"],
 breve:"Le mani con cui fai il primo rilancio quando il piatto non è ancora stato aperto.",
 lungo:"<p>Cambia con la posizione e con la profondità degli stack. Da bottone al tavolo da tre è molto largo, perché hai due soli avversari e parli per ultimo dopo il flop.</p><p>Largo non vuol dire qualunque cosa: le mani devono conservare potenziale sufficiente a giocare un flop, altrimenti apri e poi abbandoni.</p>",
 vedi:["range","min-rilancio","steal"]},

{id:"min-rilancio",it:"Min-rilancio",en:"Min-raise",cat:"Preflop",
 alias:["min-rilancio","minirilancio","mini rilancio","min raise","min-raise","mini-raise","minraise"],
 breve:"Il rilancio più piccolo consentito: il doppio del buio grande.",
 lungo:"<p>Con stack corti è la dimensione di apertura standard. Rischia poco per prendersi i bui e tiene il piatto abbastanza piccolo da lasciare spazio a tre puntate, una per strada.</p><p>Nella fase iniziale si apre sempre con questa misura, con qualsiasi mano. Cambiare dimensione a seconda della forza regalerebbe informazione gratis.</p>",
 vedi:["range-apertura","stack-effettivo"]},

{id:"shove",it:"All in",en:"Shove",cat:"Preflop",
 alias:["all in","all-in","shove","push","pushare","spingere","shovare"],
 breve:"Puntare tutto lo stack in una volta sola.",
 lungo:"<p>Con stack corti diventa l'azione principale: elimina ogni decisione successiva e massimizza la possibilità che l'avversario passi.</p><p>Chi riceve un all in non deve chiedersi se ha una bella mano, ma se ha abbastanza equity rispetto a quanto paga per quanto può vincere.</p>",
 vedi:["equity","quote-del-piatto","push-fold","fold-equity"]},

{id:"push-fold",it:"Push o fold",en:"Push/fold",cat:"Preflop",
 alias:["push o fold","push/fold","push-fold","spingi o passa"],
 breve:"Strategia con stack molto corti: ogni mano è solo o all in o passo.",
 lungo:"<p>Sotto una certa profondità rilanciare piccolo non ha senso, perché impegna già quasi tutte le fiches. Restano due sole azioni, e le scelte si ricavano da tabelle calcolate matematicamente.</p><p>È lo scenario dominante negli Spin &amp; Go a 15 bui, cioè nella maggioranza delle partite.</p>",
 vedi:["shove","stack-effettivo","nash"]},

{id:"nash",it:"Equilibrio di Nash",en:"Nash equilibrium",cat:"Matematica",
 alias:["equilibrio di nash","nash equilibrium","nash","tabelle di nash"],
 breve:"La coppia di strategie in cui nessuno dei due può guadagnare cambiando idea da solo.",
 lungo:"<p>Per le situazioni di push o fold con due giocatori esiste una soluzione calcolabile esattamente, ed è da lì che vengono le tabelle di spinta e risposta usate come riferimento.</p><p>Non è la strategia che guadagna di più: è quella che non si può sfruttare. Contro avversari che sbagliano si guadagna di più deviando.</p>",
 vedi:["push-fold","gto"]},

{id:"gto",it:"Gioco imperfettibile",en:"GTO",cat:"Matematica",
 alias:["gto","game theory optimal","gioco imperfettibile","gioco teoricamente ottimale"],
 breve:"La strategia che nessun avversario può sfruttare, anche conoscendola per intero.",
 lungo:"<p>Non punta a battere l'avversario specifico, punta a non poter essere battuta. È il pavimento sotto il quale non si scende.</p><p>Il contrario è il gioco sfruttativo: deviare apposta per punire un errore ricorrente dell'avversario, accettando di diventare a propria volta sfruttabile.</p>",
 vedi:["nash","sfruttativo"]},

{id:"sfruttativo",it:"Gioco sfruttativo",en:"Exploitative play",cat:"Concetti",
 alias:["gioco sfruttativo","sfruttativo","exploitative","exploit","sfruttare"],
 breve:"Deviare dalla strategia base per punire un errore specifico dell'avversario.",
 lungo:"<p>Se uno passa troppo, rubi di più. Se non passa mai, smetti di bluffare. Ogni deviazione ti espone a sua volta, quindi va fatta su prove, non su sensazioni.</p><p>Negli Spin &amp; Go a basso buy-in rende molto, perché gli errori degli avversari sono grossi e ripetuti.</p>",
 vedi:["gto","steal"]},

{id:"limp",it:"Limp",en:"Limp",cat:"Preflop",
 alias:["limp","limpare","limpa","limper","limpers","open limp","limpando"],
 breve:"Entrare nel piatto pagando solo il buio grande, senza rilanciare.",
 lungo:"<p>Da bottone è quasi sempre un errore: rinuncia all'iniziativa e alla possibilità di vincere subito. Chi limpa di solito ha una mano mediocre che non vuole buttare.</p><p>Dal piccolo buio invece può essere deliberato, e nelle tabelle di questa serie convive con il rilancio: alcune mani forti limpano apposta per poi spingere.</p>",
 vedi:["isolamento","trappola","steal"]},

{id:"isolamento",it:"Isolamento",en:"Isolation raise",cat:"Preflop",
 alias:["isolamento","isolare","iso","iso raise","isolation","rilancio di isolamento"],
 breve:"Rilanciare sopra un limp per restare soli contro chi è entrato debole.",
 lungo:"<p>L'obiettivo doppio è togliere di mezzo gli altri e giocare in posizione di forza contro un range che ha già dichiarato di non essere granché.</p><p>La misura tipica contro un limp è più grande di un'apertura normale, perché nel piatto ci sono già più fiches da proteggere.</p>",
 vedi:["limp","dead-money"]},

{id:"trappola",it:"Trappola",en:"Trapping",cat:"Concetti",
 alias:["trappola","trappare","trapping","slowplay","slowplayare","rallentare"],
 breve:"Nascondere una mano fortissima giocandola piano, per far parlare l'avversario.",
 lungo:"<p>Funziona solo quando c'è abbastanza stack dietro da poter recuperare le puntate perse. Con 25 bui e tre strade disponibili, di solito conviene invece costruire il piatto subito.</p><p>Va comunque previsto che qualcuno lo faccia: le tabelle contro i limp tengono conto della rara possibilità che un limp nasconda un mostro.</p>",
 vedi:["limp","cappato"]},

{id:"tre-bet",it:"3-bet",en:"3-bet",cat:"Preflop",
 alias:["3-bet","3bet","tre bet","three bet","terzo rilancio","rilancio sopra"],
 breve:"Il terzo rilancio della mano, cioè il rilancio sopra un rilancio.",
 lungo:"<p>I bui contano come prima puntata, quindi l'apertura è la seconda e il rilancio sopra è la terza. Con stack corti è quasi sempre un all in.</p><p>Dopo una 3-bet il piatto è già grande rispetto agli stack: resta spazio per una sola puntata, non per tre. Questo cambia tutto il gioco successivo.</p>",
 vedi:["shove","stack-effettivo","difesa-bb"]},

{id:"steal",it:"Furto dei bui",en:"Steal",cat:"Preflop",
 alias:["furto dei bui","rubare i bui","steal","stealing","rubare"],
 breve:"Aprire con una mano mediocre puntando soprattutto a portare a casa i bui subito.",
 lungo:"<p>Con stack corti i bui valgono molto rispetto a quello che rischi per prenderli, quindi rubare è una fonte di guadagno costante. Funziona finché gli avversari passano abbastanza.</p><p>Contro chi difende moltissimo o risponde spesso con l'all in, il range di furto va stretto.</p>",
 vedi:["range-apertura","fold-equity","sfruttativo"]},

{id:"dead-money",it:"Soldi morti",en:"Dead money",cat:"Concetti",
 alias:["soldi morti","dead money","piatto morto"],
 breve:"Le fiches già nel piatto che nessuno sta più difendendo.",
 lungo:"<p>Bui, limp e puntate abbandonate: sono soldi che si possono raccogliere senza dover vincere uno scontro. In un formato veloce ogni raccolta pesa.</p><p>Più soldi morti ci sono, più conviene attaccare anche con mani mediocri.</p>",
 vedi:["steal","isolamento","fold-equity"]},

{id:"stack-effettivo",it:"Stack effettivo",en:"Effective stack",cat:"Concetti",
 alias:["stack effettivo","stack effettivi","effective stack","stack"],
 breve:"Il più piccolo tra i due stack in gioco: è il massimo che puoi davvero vincere o perdere in quella mano.",
 lungo:"<p>Se tu hai 50 bui e l'avversario 12, in quella mano se ne giocano 12. Tutte le decisioni vanno prese guardando questo numero, non il tuo.</p><p>È la variabile che determina la strategia più di qualsiasi altra: la stessa mano vale cose diversissime a 25 bui e a 15.</p>",
 vedi:["push-fold","min-rilancio","moltiplicatore"]},

{id:"early-stage",it:"Fase iniziale",en:"Early stage",cat:"Concetti",
 alias:["fase iniziale","early stage","early-stage","primi livelli"],
 breve:"I primi livelli, quando gli stack sono ancora abbastanza profondi da poter giocare dopo il flop.",
 lungo:"<p>È la finestra in cui un giocatore preparato guadagna di più, perché ci sono ancora decisioni vere su tre strade e un errore non è fatale.</p><p>Con 15 bui questa finestra è quasi inesistente: si passa quasi subito al push o fold.</p>",
 vedi:["push-fold","stack-effettivo"]},

{id:"c-bet",it:"Puntata di continuità",en:"C-bet",cat:"Postflop",
 alias:["puntata di continuità","c-bet","cbet","c bet","continuation bet","continuity bet"],
 breve:"La puntata al flop di chi aveva rilanciato prima del flop.",
 lungo:"<p>Chi ha aperto ha raccontato una mano forte e sul flop continua la storia. Funziona perché l'avversario manca il flop circa due volte su tre.</p><p>Non va fatta sempre: la frequenza dipende da quanto la texture favorisce il tuo range. Puntare a tappeto sui flop sbagliati è un modo veloce per bruciare fiches.</p>",
 vedi:["texture","vantaggio-di-range","flop"]},

{id:"texture",it:"Texture",en:"Board texture",cat:"Postflop",
 alias:["texture","tessitura","struttura del board","board texture","asciutto","bagnato","dry","wet"],
 breve:"Com'è fatto il flop: carte alte o basse, collegate o slegate, dello stesso seme o no.",
 lungo:"<p>Si distingue tra flop asciutti, con carte lontane e nessun progetto evidente, e flop bagnati, pieni di scale e colori possibili.</p><p>Sugli asciutti chi ha l'iniziativa punta spesso e piccolo. Sui bagnati l'avversario ha molte più mani che possono continuare, quindi si punta meno spesso e più grosso.</p>",
 vedi:["c-bet","vantaggio-di-range","board"]},

{id:"board",it:"Board",en:"Board",cat:"Postflop",
 alias:["board","carte comuni","tavolo"],
 breve:"Le carte comuni scoperte al centro: flop, turn e river.",
 lungo:"<p>Appartengono a entrambi i giocatori, quindi ogni carta che esce cambia contemporaneamente la forza di tutte e due le mani e di tutti e due i range.</p>",
 vedi:["flop","texture"]},

{id:"vantaggio-di-range",it:"Vantaggio di range",en:"Range advantage",cat:"Postflop",
 alias:["vantaggio di range","vantaggio del range","range advantage","equity advantage"],
 breve:"Quando su un certo board il tuo insieme di mani è complessivamente più forte di quello dell'avversario.",
 lungo:"<p>Non riguarda la mano che hai, ma tutte quelle che potresti avere. Se hai aperto da bottone e il flop è asso re sette, il tuo range contiene molti più assi e re di quello di chi ha solo pagato.</p><p>Su un flop nove otto sei il vantaggio evapora o passa dall'altra parte, perché quelle carte si incastrano meglio con il range di chi ha difeso.</p>",
 vedi:["texture","c-bet","cappato"]},

{id:"cappato",it:"Range cappato",en:"Capped range",cat:"Concetti",
 alias:["cappato","cappate","capped","range cappato","capped range"],
 breve:"Un range senza le mani più forti, perché con quelle avresti giocato diversamente.",
 lungo:"<p>Se con i mostri avresti rilanciato, allora quando ti limiti a pagare il tuo range ha un tetto: coppie medie e progetti, non fortissime.</p><p>Riconoscere un range cappato autorizza ad applicare pressione, perché l'avversario non ha quasi mai di che pagare fino in fondo.</p>",
 vedi:["range","vantaggio-di-range","trappola"]},

{id:"equity",it:"Equity",en:"Equity",cat:"Matematica",
 alias:["equity","quota di piatto"],
 breve:"La quota del piatto che ti spetta in media, cioè quanto spesso vinci lo scontro sul lungo periodo.",
 lungo:"<p>Se vinci il 40% delle volte contro il range avversario, la tua equity in un piatto da 1000 è 400. Non è quello che vinci stavolta, è la media su moltissime ripetizioni.</p><p>Si confronta sempre con quanto stai pagando: mettere 460 per vincerne 1010 richiede circa il 45%, non il 50%.</p>",
 vedi:["quote-del-piatto","valore-atteso"]},

{id:"quote-del-piatto",it:"Quote del piatto",en:"Pot odds",cat:"Matematica",
 alias:["quote del piatto","pot odds","quote","odds"],
 breve:"Il rapporto tra quanto devi pagare e quanto puoi vincere: dice l'equity minima che ti serve.",
 lungo:"<p>Si divide quello che metti per il totale del piatto dopo averlo messo. Pagare 100 in un piatto che diventa 400 richiede il 25%.</p><p>È il motivo per cui dal grande buio ci si difende con mani deboli: hai già dentro un buio, quindi il prezzo per continuare è basso.</p>",
 vedi:["equity","difesa-bb"]},

{id:"valore-atteso",it:"Valore atteso",en:"Expected value",cat:"Matematica",
 alias:["valore atteso","ev","expected value"],
 breve:"Quanto rende in media una decisione, pesando ogni esito per la sua probabilità.",
 lungo:"<p>Si sommano gli esiti possibili moltiplicati per quanto spesso accadono. Se una mossa vince 70 nel 74% dei casi e perde 177 nel 26%, il valore atteso è 70×0,74 meno 177×0,26.</p><p>Giocare bene significa scegliere ogni volta l'azione con il valore atteso più alto, indipendentemente da come è andata l'ultima volta.</p>",
 vedi:["equity","fold-equity","varianza"]},

{id:"fold-equity",it:"Equity di piega",en:"Fold equity",cat:"Matematica",
 alias:["equity di piega","fold equity","fold-equity"],
 breve:"Il valore che ricavi dalle volte in cui l'avversario passa e ti lascia il piatto.",
 lungo:"<p>Quando spingi vinci in due modi: perché lui passa, o perché paga e tu vinci lo scontro. Il primo è quasi sempre la parte più grossa del guadagno con stack corti.</p><p>Contro chi non passa mai la fold equity è zero, e restano solo le carte.</p>",
 vedi:["shove","valore-atteso","steal"]},

{id:"blocker",it:"Blocker",en:"Blocker",cat:"Concetti",
 alias:["blocker","blockers","bloccante","carta bloccante"],
 breve:"Una carta in tua mano che riduce il numero di mani forti che l'avversario può avere.",
 lungo:"<p>Se hai un asso, le combinazioni di assi disponibili per lui scendono. Con un re in mano è meno probabile che lui abbia KK o AK.</p><p>Conta soprattutto quando spingi come bluff: un blocker rende meno probabile che ti paghino.</p>",
 vedi:["combo","shove"]},

{id:"combo",it:"Combinazione",en:"Combo",cat:"Concetti",
 alias:["combinazione","combinazioni","combo","combos"],
 breve:"Ogni singola versione di una mano contando i semi: 6 per le coppie, 4 se dello stesso seme, 12 altrimenti.",
 lungo:"<p>Le mani sono 169 ignorando i semi, 1326 contandoli. Serve per misurare quanto è largo un range davvero: un range fatto solo di coppie occupa molte caselle ma pesa poco.</p><p>Da qui vengono tutte le percentuali accanto alle tabelle.</p>",
 vedi:["range","griglia","blocker"]},

{id:"griglia",it:"Griglia dei range",en:"Range grid",cat:"Concetti",
 alias:["griglia dei range","griglia","matrice","range grid","hand matrix"],
 breve:"La tabella 13×13 che rappresenta tutte le 169 mani di partenza.",
 lungo:"<p>Le coppie sulla diagonale, sopra le mani dello stesso seme, sotto quelle di semi diversi. Gli assi in alto a sinistra, le carte basse in basso a destra.</p><p>Ogni casella colorata secondo l'azione prevista: si legge tutta la strategia in un colpo d'occhio.</p>",
 vedi:["range","combo"]},

{id:"suited",it:"Stesso seme",en:"Suited",cat:"Concetti",
 alias:["stesso seme","suited","suitate","di cuori","offsuit","semi diversi","spaiate"],
 breve:"Due carte dello stesso seme (suited) o di semi diversi (offsuit).",
 lungo:"<p>Nella notazione si indica con una s o una o finale: AKs e AKo. Le coppie non hanno suffisso.</p><p>Lo stesso seme vale parecchio con stack corti: aggiunge la possibilità di colore e alza l'equity contro quasi tutto, che è esattamente ciò che serve quando si finisce spesso all in.</p>",
 vedi:["combo","connettori"]},

{id:"connettori",it:"Connettori",en:"Connectors",cat:"Concetti",
 alias:["connettori","connettore","suited connector","suited connectors","connectors"],
 breve:"Due carte consecutive, spesso dello stesso seme: 76s, 98s.",
 lungo:"<p>Valgono poco in valore assoluto ma tanto in potenziale, perché fanno scale e colori. Funzionano bene proprio contro i range larghi e deboli.</p><p>È il motivo per cui 76s può spingere contro un limp: quando lo pagano, raramente è dominato senza speranza.</p>",
 vedi:["suited","shove","limp"]},

{id:"difesa-bb",it:"Difesa del grande buio",en:"Big blind defence",cat:"Preflop",
 alias:["difesa del grande buio","difesa del big blind","difendere il big blind","bb defence","bb defense","difesa"],
 breve:"Le mani con cui continui dal grande buio di fronte a un'apertura, invece di passare.",
 lungo:"<p>Grazie alle quote si difende molto più largo di quanto si aprirebbe. Con stack corti le opzioni sono tre e non due: passare, pagare, o spingere.</p><p>Difendere troppo poco rende il furto dei bui automaticamente redditizio per l'avversario. Difendere troppo ti fa giocare troppi piatti fuori posizione.</p>",
 vedi:["big-blind","quote-del-piatto","tre-bet"]},

{id:"flop",it:"Flop",en:"Flop",cat:"Postflop",
 alias:["flop"],
 breve:"Le prime tre carte comuni, scoperte insieme dopo il primo giro di puntate.",
 lungo:"<p>È il momento in cui la mano prende forma: hai visto cinque delle sette carte finali, quindi la maggior parte dell'informazione è già sul tavolo.</p>",
 vedi:["texture","c-bet","board"]},

{id:"icm",it:"ICM",en:"ICM",cat:"Matematica",
 alias:["icm","independent chip model"],
 breve:"Il modello che traduce le fiches in soldi quando la struttura dei premi paga più posizioni.",
 lungo:"<p>Nei tornei le fiches non valgono linearmente: raddoppiare lo stack non raddoppia il guadagno atteso. L'ICM stima quanto vale in denaro il tuo stack date la struttura e gli stack degli altri.</p><p>Conta poco quando vince tutto il primo, e parecchio sui moltiplicatori alti dove pagano tre posizioni.</p>",
 vedi:["moltiplicatore","spin-go"]}
];
